### ISSUE TITLE
fatal error: QImageCapture: No such file or directory

### ISSUE THREAD

**Issue by Tellie** [SiderealArt/Daruma#10]
Hi

WHen compiling it with QT5 v5.14.2 i get the above error.
Where to find that header?

**Comment by 5idereal** [comment]
Hi!
The header is only in [Qt6](https://doc.qt.io/qt-6/qimagecapture.html), and you also need to install the multimedia module.
Sorry for the inconvenience!

**Comment by Tellie** [comment]
Hi,

Aha ic...
So it's only for qt6

Op do 3 mrt. 2022 03:07 schreef SiderealArt ***@***.***>:
